language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker run -p 6379:6379 -d redislabs/redisgraph

cache: pip

install:
  - pip install -r requirements.txt

script:
  - python3 -m unittest discover tests/
